version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/caffelito
      - SECRET_KEY=caffelito_secret_key
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: caffelito
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
